name: jupyterdask
channels:
 - conda-forge
dependencies:
  - python=3.11
  - dask[complete]
  - dask-jobqueue
  - fsspec
  - h5netcdf
  - matplotlib
  - xarray
  - zarr
  - pip
  - pip:
    - dcachefs
